image: ondrejsika/ci

stages:
    - build
    - test
    - deploy_dev
    - deploy_prod

variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TEST: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG

before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

.build_template: &build_template
    stage: build
    script:
        - docker-compose build
        - docker-compose push
build:
    <<: *build_template
    only:
        changes:
            - docker-compose.yml
            - server/**

build_test:
    <<: *build_template
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
    only:
        changes:
            - docker-compose.yml
            - docker-compose-test.yml
            - test/**

test:
    stage: test
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
        COMPOSE_PROJECT_NAME: $CI_JOB_ID
    script:
        - docker-compose pull
        - docker-compose run test
        - docker-compose down
    only:
        changes:
            - docker-compose*.yml
            - test/**
            - server/**

.dev_template: &dev_template
    stage: deploy_dev
    tags:
        - prod
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
        HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.prod.sikademo.com

.deploy_template: &deploy_template
    tags:
        - prod
    script:
        - docker-compose pull
        - docker-compose up -d

deploy_dev:
    <<: *deploy_template
    <<: *dev_template
    environment:
        name: $CI_COMMIT_REF_SLUG
        url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.prod.sikademo.com
        on_stop: stop_deploy_dev

stop_deploy_dev:
    when: manual
    <<: *dev_template
    script:
        - docker-compose down
    environment:
        name: $CI_COMMIT_REF_SLUG
        action: stop

deploy_prod:
    stage: deploy_prod
    only:
        - master
    <<: *deploy_template
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml
        COMPOSE_PROJECT_NAME: $CI_PROJECT_PATH_SLUG
        HOST: prod.prod.sikademo.com
    environment:
        name: $CI_COMMIT_REF_SLUG
        url: https://prod.prod.sikademo.com