image: ondrejsika/ci

stages:
    - build
    - test
    - deploy_dev
    - deploy_prod

variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TEST: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG

before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

.build_template: &build_template
    stage: build
    script:
        - docker-compose build
        - docker-compose push
build:
    <<: *build_template
    only:
        changes:
            - docker-compose.yml
            - server/**

build_test:
    <<: *build_template
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
    only:
        changes:
            - docker-compose*.yml
            - test/**