image: ondrejsika/ci

stages:
    - build
    - test
    - deploy_dev
    - deploy_prod

variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
    stage: build
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker-compose build
        - docker-compose push
    only:
        changes:
            - docker-compose.yml
            - server/**